package preparation.revise_1.mor;

import java.io.IOException;

public class Demo9 {

    public static void main(String[] args) {
        NonBase nonBase = new NonBase();
        nonBase.method(10);
    }

    static class Base<T> {
        public void method(T data){
            System.out.println("Setting data in Base : "+data);
        }
    }

    static class NonBase extends Base<Integer> {

        @Override
        public void method(Integer data) {
            System.out.println("Setting data in NonBase : "+data);
        }
    }

    /*
         Bridge Method Generated by Compiler
         ===================================
        // Bridge method generated by the compiler
        public void setData(Object data) {
          setData((Integer) data); // Cast to the specific type
        }
    */

}
