package java7andbelow.features.oops;

public class _30_Default_Constructor {

    public static void main(String[] args) {

        /*
            Default Constructor
            ===================
            1.	Compiler is responsible to generate the default constructor. But not the JVM.

            2.	If we are not writing any constructor, then only compiler will generate the default
                constructor. If we are writing at least one constructor then compiler won’t generate
                the constructor.

            3.	Every class in Java contains constructor either generated by the compiler or customized
                constructor provided by the programmer but not both of them simultaneously.
        */

        /*
            Prototype of Default Constructor
            ================================
            1.	It’s always No Arg constructor.

            2.	The access modifier of default constructor is same as access modifier
                of the class (This rule is applicable only for public and default).

            3.	It contains only one line (super ()). It’s a No Arg call to super class
                constructor.
        */

        /*
            // Programmer’s code
            class Test {
            }

            // Compiler’s code
            class Test {
                Test () {
                    Super ();
                }
            }

            // Programmer’s code
            public class Test {
            }

            // Compiler’s code
            public class Test {
            public Test () {
             Super ();
            }
            }

            // Programmer’s code
            public class Test {
            void Test () {
            }
            }

            // Compiler’s code
            public class Test {
            public Test () {
             Super ();
            }
            void Test () {
            }
            }

            // Programmer’s code
            class Test {
            Test () {
            }
            }

            // Compiler’s code
            class Test {
            Test () {
             Super ();
            }
            }

            // Programmer’s code
            class Test {
            Test (int i) {
            super ();
            }
            }

            // Compiler’s code
            class Test {
            Test (int i) {
            super ();
            }
            }

            // Programmer’s code
            class Test {
            Test () {
            this (10);
            }
            Test (int i) {
            }
            }

            // Compiler’s code
            class Test {
            Test () {
            this (10);
            }
            Test (int i) {
            super ();
            }
            }
        */
    }
}
