package beforeJava8.features.multi_threading;

public class _08_Thread_Name {
    public static void main(String[] args) {
        /*
            Define Thread Name (Getting and Setting name of a Thread)
            =========================================================
            Every thread in Java has some name, it may be default name generated by JVM
            or customized name provided by the Programmer.

            We can get and set name of a thread by using the following 2 methods of Thread
            class,

            public final string getName();
            public final void setName(String name);
        */
        System.out.println(Thread.currentThread().getName());
        MyThread2 myThread2 = new MyThread2();

        // Thread - Get Name
        System.out.println(myThread2.getName());

        // Thread - Set Name
        Thread.currentThread().setName("Jack");

        System.out.println(Thread.currentThread().getName());
    }
}
class MyThread2 extends Thread {
}